### PR TITLE
add compatibility to Pimcore >= 10.5

### PR DESCRIPTION
**Pull request by hethehe**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #80

Fixes the error:
`Too few arguments to function ProcessManagerBundle\Model\Process\Listing\Dao::prepareQueryBuilderForTotalCount(), 1 passed in /var/www/html/vendor/dpfaffenbauer/process-manager/src/ProcessManagerBundle/Model/Process/Listing/Dao.php on line 116 and exactly 2 expected`

Since Pimcore 10.5 the method Dao::prepareQueryBuilderForTotalCount() needs 2 parameters:
`protected function prepareQueryBuilderForTotalCount(QueryBuilder $queryBuilder, string $identifierColumn): void`

So that we don't break this version to (or have to change the minimum required Pimcore Version to 10.5) it's fixed with a workaround.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
please also change the dependency in the composer.json to Pimcore ^10.5

**Comment by hethehe** [comment]
shouldn't be necessary, see:
So that we don't break this version to (or have to change the minimum required Pimcore Version to 10.5) it's fixed with a workaround. 
OK?

**Comment by dpfaffenbauer** [comment]
@hethehe alright then
@dkarlovi wdyt?

**Comment by dkarlovi** [comment]
Seems OK to me.

**Comment by hethehe** [comment]
@dpfaffenbauer ping ;)

**Comment by dpfaffenbauer** [comment]
@hethehe sorry. all good, will merge

**Pull request merged**
